# ============================================================
# PROXMOX VE CLUSTER NODES
# ============================================================
[pve]
node1 ansible_host="{{ node_ips['node1'] }}"
node2 ansible_host="{{ node_ips['node2'] }}"

[all:vars]
ansible_user=root
